/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import aplikasipenjualannetbeansk04.koneksi;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
/**
 *
 * @author labprog233
 */
public class distributorbarang extends javax.swing.JFrame {

     private DefaultTableModel model;
    /**
     * Creates new form distributorbarang
     */
     public distributorbarang() {
        initComponents();
        loadData();
        kosong();
        setEnabledFalse();
        btnsave.setEnabled(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btncencel.setEnabled(false);
    }

    public void loadData(){
        model = new DefaultTableModel();
               
        model.getDataVector().removeAllElements();
        
        model.fireTableDataChanged();
        
        txttebel.setModel(model);
        model.addColumn("IDDistributor");
        model.addColumn("NamaDistributor");
        model.addColumn("Alamat");
        model.addColumn("KotaAsal");
        model.addColumn("Email");
        model.addColumn("Telepon");
        
        try{
            
            String sql = "SELECT * FROM tbldistributor";
            
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
                
                model.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6)
                });
            }
            txttebel.setModel(model);
        }catch(SQLException e){
            System.out.println("Terjadi Error"); 
        }
    }
    
    public void kosong(){
        txtid.setText(null);
        txtdistributor.setText(null);
        txtalamat.setText(null);
        txtkota.setText(null);
        txtemail.setText(null);
        txttelpon.setText(null);
    }
    
    public void setEnabledFalse(){
        txtid.setEnabled(false);
        txtdistributor.setEnabled(false);
        txtalamat.setEnabled(false);
        txtkota.setEnabled(false);
        txtemail.setEnabled(false);
        txttelpon.setEnabled(false);
    }
    
    public void setEnabledTrue(){
        txtid.setEnabled(true);
        txtdistributor.setEnabled(true);
        txtalamat.setEnabled(true);
        txtkota.setEnabled(true);
        txtemail.setEnabled(true);
        txttelpon.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtdistributor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        txtkota = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelpon = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txttebel = new javax.swing.JTable();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncencel = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Masukan Data Distributor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 22, -1, -1));

        jLabel2.setText("ID Distributor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setText("Nama Distributor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setText("Alamat Distributor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setText("Kota Asal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel7.setText("Telpon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, -1));

        txtdistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdistributorActionPerformed(evt);
            }
        });
        getContentPane().add(txtdistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 180, -1));

        txtkota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 180, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 180, -1));

        txttelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelponActionPerformed(evt);
            }
        });
        getContentPane().add(txttelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 180, -1));

        txttebel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txttebel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttebelMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(txttebel);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 387, 530, 150));

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        btncencel.setText("Cencel");
        btncencel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncencelActionPerformed(evt);
            }
        });
        getContentPane().add(btncencel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        btnadd.setText("add new");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelponActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
          int i = txttebel.getSelectedRow();
        
        if(i == -1){
            //tidak ada baris tewrseleksi
            JOptionPane.showMessageDialog(this, "harap pilih data terlebih dahulu", "error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String id = (String) model.getValueAt(i, 0);
        String nama = txtdistributor.getText();
        String alamat = txtalamat.getText();
        String kota = txtkota.getText();
        String email = txtemail.getText();
        String telpon = txttelpon.getText();
        
        try{
            
           Connection c = koneksi.getKoneksi();

            String sql = "UPDATE tbldistributor SET NamaDistributor = ?, Alamat = ?, KotaAsal = ?, Email = ?, Telpon = ? WHERE IDDistributor = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            
            p.setString(1, nama);
            p.setString(2, alamat);
            p.setString(3, kota);
            p.setString(4, email);
            p.setString(5, telpon);
            p.setString(6, id);
            
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null,"Ubah Data Berhasil");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Terjadi ERROR" + e.getMessage());
        }finally{
            loadData();
            kosong();
        }
        
        setEnabledFalse();
        btnsave.setEnabled(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btncencel.setEnabled(false);
        btnadd.setEnabled(true);

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String id = txtid.getText();
        String nama = txtdistributor.getText();
        String alamat = txtalamat.getText();
        String kota = txtkota.getText();
        String email = txtemail.getText();
        String telpon = txttelpon.getText();
        
        if ("".equals(id) || "".equals(nama) ||
                "".equals(alamat)||"".equals(kota) || 
                "".equals(email) || "".equals(telpon))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "error", JOptionPane.WARNING_MESSAGE);
        } else {
            
            try{
                Connection c = koneksi.getKoneksi();
                String sql = "insert into tbldistributor value (?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                
                p.setString(1, id);
                p.setString(2, nama);
                p.setString(3, alamat);
                p.setString(4, kota);
                p.setString(5, email);
                p.setString(6, telpon);
                
                p.executeUpdate();
                p.close();
                
                JOptionPane.showMessageDialog(null, "penyimpanan data berhasil");
              
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }finally{
                loadData();
                kosong();
                setEnabledTrue();
               btnadd.setEnabled(true);
            }
        }
        
        setEnabledFalse();
        btnsave.setEnabled(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btncencel.setEnabled(false);
        btnadd.setEnabled(true);
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txttebelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttebelMouseClicked
        // TODO add your handling code here:
         int baris = txttebel.getSelectedRow();
        
        if (baris == -1) {
            return;
        }
        
        String IDDistributor = txttebel.getValueAt(baris, 0).toString();
        String NamaDistributor = txttebel.getValueAt(baris, 1).toString();
        String Alamat = txttebel.getValueAt(baris, 2).toString();
        String KotaAsal = txttebel.getValueAt(baris, 3).toString();
        String Email = txttebel.getValueAt(baris, 4).toString();
        String Telepon = txttebel.getValueAt(baris, 5).toString();
        txtid.setText(IDDistributor);
        txtdistributor.setText(NamaDistributor);
        txtalamat.setText(Alamat);
        txtkota.setText(KotaAsal);
        txtemail.setText(Email);
        txttelpon.setText(Telepon);
        
        setEnabledTrue();
        btnupdate.setEnabled(true);
        btndelete.setEnabled(true);
        btncencel.setEnabled(true);
        btnadd.setEnabled(false);              

    }//GEN-LAST:event_txttebelMouseClicked

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyPressed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i = txttebel.getSelectedRow();
        
        if(i == -1){
            //tidak ada baris tewrseleksi
            JOptionPane.showMessageDialog(this, "Harap Pilih Data Terlebih Dahulu", "ERROR", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String id = (String) model.getValueAt(i, 0);
        
        try{
            Connection c = koneksi.getKoneksi();
            
            String sql = "DELETE FROM tbldistributor WHERE IDDistributor = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi ERROR");
        }finally {
            loadData();
            kosong();
        }
        
        setEnabledFalse();
        btnsave.setEnabled(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btncencel.setEnabled(false);
        btnadd.setEnabled(true);

    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncencelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncencelActionPerformed
        // TODO add your handling code here:
          kosong();
        setEnabledFalse();
        btnsave.setEnabled(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btncencel.setEnabled(false);
        btnadd.setEnabled(true);                                       

    }//GEN-LAST:event_btncencelActionPerformed

    private void txtkotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkotaActionPerformed

    private void txtdistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdistributorActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtdistributorActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        setEnabledTrue();
        btnsave.setEnabled(true);
        btnupdate.setEnabled(true);
        btndelete.setEnabled(true);
        btncencel.setEnabled(true);
        btnadd.setEnabled(false);
    }//GEN-LAST:event_btnaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(distributorbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(distributorbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(distributorbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(distributorbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new distributorbarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncencel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtdistributor;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTable txttebel;
    private javax.swing.JTextField txttelpon;
    // End of variables declaration//GEN-END:variables
}
