
import aplikasi.penjualan.netbeans.k04.Koneksi;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



public class Jenis extends javax.swing.JFrame {

    /**
     * Creates new form Jenis
     */
    private static Connection conn;
    public Jenis() {
        conn=   Koneksi.getKoneksi();
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhasil = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("JENIS BARANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 26, -1, -1));

        jLabel2.setText("Kode Jenis");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 57, -1, -1));

        jLabel3.setText("Nama Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 97, -1, -1));

        txtjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjenisActionPerformed(evt);
            }
        });
        jPanel1.add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 54, 138, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 94, 127, -1));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 134, -1, -1));

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 134, -1, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 134, -1, -1));

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 134, -1, -1));

        tblhasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode Jenis", "Nama "
            }
        ));
        tblhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhasil);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 175, 542, 314));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjenisActionPerformed
        
    }//GEN-LAST:event_txtjenisActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
                
    String kode = txtjenis.getText();
    String nama = txtnama.getText();
    
        if (nama.isEmpty() || kode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom wajib di isi !","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String sql = "INSERT INTO tbljenis VALUES(?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, kode);
            st.setString(2, nama);
           
            int rowInserted = st.executeUpdate();
            if(rowInserted >0){
                JOptionPane.showMessageDialog(this, "Data sukses");
                resetform();
                loadData();
                
            };
            st.close();
        } catch (Exception e) {
             Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
    int pilih = tblhasil.getSelectedRow();
    String id = tblhasil.getValueAt(pilih, 0).toString();
    String kode = txtjenis.getText();
    String nama = txtnama.getText();
    
        if (nama.isEmpty() || kode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom wajib di isi !","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String sql = "UPDATE  tbljenis SET Jenis =? WHERE KodeJenis=?";
            PreparedStatement st = conn.prepareStatement(sql);
             st.setString(1, nama);
            st.setString(2, id);
           
            int rowInserted = st.executeUpdate();
            if(rowInserted >0){
                JOptionPane.showMessageDialog(this, "Data berhasil di perbaharui");
                resetform();
                loadData();
                
            };
            st.close();
        } catch (Exception e) {
             Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
        }  
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tblhasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhasilMouseClicked
        int pilih = tblhasil.getSelectedRow();
        if(pilih!=-1){
        String kode = tblhasil.getValueAt(pilih, 0).toString();
        String nama = tblhasil.getValueAt(pilih, 1).toString();
        txtjenis.setText(kode);
        txtnama.setText(nama);
        }
        
//        btnupdate.setEnabled(true);
//        btntambah.setEnabled(false);
//        btnhapus.setEnabled(true);
    }//GEN-LAST:event_tblhasilMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int pilih = tblhasil.getSelectedRow();
        if(pilih==-1){
        JOptionPane.showMessageDialog(this, "Pilih data yg ingin dihapus", "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
        String id = tblhasil.getValueAt(pilih, 0).toString();
        
            try {
                String sql = "DELETE FROM tbljenis WHERE KodeJenis=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, id);
                
                int rowDelete = st.executeUpdate();
                if(rowDelete > 0){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    resetform();
                    loadData();
                }
                st.close();
            } catch (Exception e) {
                Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jenis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhasil;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

   

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblhasil.getModel();
           model.setRowCount(0);
           try {
               String sql = "Select * From tbljenis";
               PreparedStatement st = conn.prepareStatement(sql);
               ResultSet rs = st.executeQuery();
               while(rs.next()){
                   int id = rs.getInt("KodeJenis");
                   String Nama = rs.getString("Jenis");
                   Object[] rowData = {id,Nama};
                   model.addRow(rowData);
                }
                rs.close();
                st.close();
                   

           } catch (Exception e) {
                Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
           }
    }

    private void resetform() {
        txtjenis.setText("");
        txtnama.setText("");
    }
}
